language: c

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

install:
  - git clone https://github.com/nsf/termbox
  - pushd termbox && ./waf configure && ./waf && sudo ./waf install && popd

script: make test
