language: c

dist: trusty
sudo: false

script: make && make test

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COVERAGE=1

after_success:
  - [ $COVERAGE = 1 ] && bash <(curl -s https://codecov.io/bash)
